buildscript {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.21'
        classpath 'com.google.devtools.ksp:symbol-processing-gradle-plugin:2.2.21-2.0.5'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.57.2'
    }

    configurations.classpath {
        resolutionStrategy {
            force 'com.google.guava:guava:33.4.0-jre'
            force 'com.google.protobuf:protobuf-java:4.27.5'
            force 'com.google.protobuf:protobuf-kotlin:4.27.5'
            force 'com.google.protobuf:protobuf-javalite:4.27.5'
            force 'io.opentelemetry:opentelemetry-api:1.62.0'
            force 'org.jetbrains.kotlin:kotlin-stdlib:2.2.21'
            force 'org.jetbrains.kotlin:kotlin-stdlib-common:2.2.21'
            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.2.21'
            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.21'
            force 'io.netty:netty-common:4.1.133.Final'
            force 'io.netty:netty-buffer:4.1.133.Final'
            force 'io.netty:netty-transport:4.1.133.Final'
            force 'io.netty:netty-resolver:4.1.133.Final'
            force 'io.netty:netty-codec:4.1.133.Final'
            force 'io.netty:netty-codec-http:4.1.133.Final'
            force 'io.netty:netty-codec-http2:4.1.133.Final'
            force 'io.netty:netty-handler:4.1.133.Final'
            force 'io.netty:netty-handler-proxy:4.1.133.Final'
            force 'io.netty:netty-codec-socks:4.1.133.Final'
            force 'io.netty:netty-transport-native-unix-common:4.1.133.Final'
            force 'org.apache.commons:commons-compress:1.28.0'
            force 'org.apache.commons:commons-lang3:3.18.0'
            force 'org.bitbucket.b_c:jose4j:0.9.6'
            force 'org.bouncycastle:bcpg-jdk18on:1.84'
            force 'org.bouncycastle:bcpkix-jdk18on:1.84'
            force 'org.bouncycastle:bcprov-jdk18on:1.84'
            force 'org.bouncycastle:bcutil-jdk18on:1.84'
            force 'org.jdom:jdom2:2.0.6.1'
        }
    }
}

allprojects {
    configurations.configureEach {
        resolutionStrategy {
            force 'com.google.guava:guava:33.4.0-jre'
            force 'com.google.protobuf:protobuf-java:4.27.5'
            force 'com.google.protobuf:protobuf-kotlin:4.27.5'
            force 'com.google.protobuf:protobuf-javalite:4.27.5'
            force 'io.opentelemetry:opentelemetry-api:1.62.0'
            force 'org.jetbrains.kotlin:kotlin-stdlib:2.2.21'
            force 'org.jetbrains.kotlin:kotlin-stdlib-common:2.2.21'
            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:2.2.21'
            force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.21'
            force 'io.netty:netty-common:4.1.133.Final'
            force 'io.netty:netty-buffer:4.1.133.Final'
            force 'io.netty:netty-transport:4.1.133.Final'
            force 'io.netty:netty-resolver:4.1.133.Final'
            force 'io.netty:netty-codec:4.1.133.Final'
            force 'io.netty:netty-codec-http:4.1.133.Final'
            force 'io.netty:netty-codec-http2:4.1.133.Final'
            force 'io.netty:netty-handler:4.1.133.Final'
            force 'io.netty:netty-handler-proxy:4.1.133.Final'
            force 'io.netty:netty-codec-socks:4.1.133.Final'
            force 'io.netty:netty-transport-native-unix-common:4.1.133.Final'
            force 'org.apache.commons:commons-compress:1.28.0'
            force 'org.apache.commons:commons-lang3:3.18.0'
            force 'org.bitbucket.b_c:jose4j:0.9.6'
            force 'org.bouncycastle:bcpg-jdk18on:1.84'
            force 'org.bouncycastle:bcpkix-jdk18on:1.84'
            force 'org.bouncycastle:bcprov-jdk18on:1.84'
            force 'org.bouncycastle:bcutil-jdk18on:1.84'
            force 'org.jdom:jdom2:2.0.6.1'
        }
    }
}
