// Autogenerated from Pigeon (v27.2.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, omit_local_variable_types, omit_obvious_local_variable_types

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Pigeon contract shared by the Flutter store and the authoritative Kotlin
/// module core. All business state comes from the host; Flutter only owns UI
/// preferences such as filters and search history.
class NativeModule {
  NativeModule({
    this.id,
    this.name,
    this.shortDescription,
    this.description,
    this.versionName,
    this.versionCode,
    this.installedVersionCode,
    this.runtime,
    this.deliveryType,
    this.state,
    this.route,
    this.entryClass,
    this.entry,
    this.serviceType,
    this.launcherId,
    this.iconUrl,
    this.category,
    this.fileSize,
    this.builtIn,
    this.required,
    this.featured,
    this.enabled,
    this.updateAvailable,
    this.compatible,
    this.rollbackAvailable,
    this.minHostVersionCode,
    this.maxHostVersionCode,
    this.permissions,
    this.permissionsDescription,
    this.dependencies,
    this.tags,
    this.screenshots,
    this.changelog,
    this.detailsJson,
    this.privacyJson,
  });

  String? id;

  String? name;

  String? shortDescription;

  String? description;

  String? versionName;

  int? versionCode;

  int? installedVersionCode;

  String? runtime;

  String? deliveryType;

  String? state;

  String? route;

  String? entryClass;

  String? entry;

  String? serviceType;

  String? launcherId;

  String? iconUrl;

  String? category;

  int? fileSize;

  bool? builtIn;

  bool? required;

  bool? featured;

  bool? enabled;

  bool? updateAvailable;

  bool? compatible;

  bool? rollbackAvailable;

  int? minHostVersionCode;

  int? maxHostVersionCode;

  List<String?>? permissions;

  List<String?>? permissionsDescription;

  List<String?>? dependencies;

  List<String?>? tags;

  List<String?>? screenshots;

  List<String?>? changelog;

  /// 模块详情 JSON 字符串（#11.1）：valueDescription/audience/offlineCapability 等
  String? detailsJson;

  /// 隐私卡 JSON 字符串（#11.2）：localData/cloudData/networkDomains 等
  String? privacyJson;

  List<Object?> _toList() {
    return <Object?>[
      id,
      name,
      shortDescription,
      description,
      versionName,
      versionCode,
      installedVersionCode,
      runtime,
      deliveryType,
      state,
      route,
      entryClass,
      entry,
      serviceType,
      launcherId,
      iconUrl,
      category,
      fileSize,
      builtIn,
      required,
      featured,
      enabled,
      updateAvailable,
      compatible,
      rollbackAvailable,
      minHostVersionCode,
      maxHostVersionCode,
      permissions,
      permissionsDescription,
      dependencies,
      tags,
      screenshots,
      changelog,
      detailsJson,
      privacyJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeModule decode(Object result) {
    result as List<Object?>;
    return NativeModule(
      id: result[0] as String?,
      name: result[1] as String?,
      shortDescription: result[2] as String?,
      description: result[3] as String?,
      versionName: result[4] as String?,
      versionCode: result[5] as int?,
      installedVersionCode: result[6] as int?,
      runtime: result[7] as String?,
      deliveryType: result[8] as String?,
      state: result[9] as String?,
      route: result[10] as String?,
      entryClass: result[11] as String?,
      entry: result[12] as String?,
      serviceType: result[13] as String?,
      launcherId: result[14] as String?,
      iconUrl: result[15] as String?,
      category: result[16] as String?,
      fileSize: result[17] as int?,
      builtIn: result[18] as bool?,
      required: result[19] as bool?,
      featured: result[20] as bool?,
      enabled: result[21] as bool?,
      updateAvailable: result[22] as bool?,
      compatible: result[23] as bool?,
      rollbackAvailable: result[24] as bool?,
      minHostVersionCode: result[25] as int?,
      maxHostVersionCode: result[26] as int?,
      permissions: (result[27] as List<Object?>?)?.cast<String?>(),
      permissionsDescription: (result[28] as List<Object?>?)?.cast<String?>(),
      dependencies: (result[29] as List<Object?>?)?.cast<String?>(),
      tags: (result[30] as List<Object?>?)?.cast<String?>(),
      screenshots: (result[31] as List<Object?>?)?.cast<String?>(),
      changelog: (result[32] as List<Object?>?)?.cast<String?>(),
      detailsJson: result[33] as String?,
      privacyJson: result[34] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeModule || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(name, other.name) && _deepEquals(shortDescription, other.shortDescription) && _deepEquals(description, other.description) && _deepEquals(versionName, other.versionName) && _deepEquals(versionCode, other.versionCode) && _deepEquals(installedVersionCode, other.installedVersionCode) && _deepEquals(runtime, other.runtime) && _deepEquals(deliveryType, other.deliveryType) && _deepEquals(state, other.state) && _deepEquals(route, other.route) && _deepEquals(entryClass, other.entryClass) && _deepEquals(entry, other.entry) && _deepEquals(serviceType, other.serviceType) && _deepEquals(launcherId, other.launcherId) && _deepEquals(iconUrl, other.iconUrl) && _deepEquals(category, other.category) && _deepEquals(fileSize, other.fileSize) && _deepEquals(builtIn, other.builtIn) && _deepEquals(required, other.required) && _deepEquals(featured, other.featured) && _deepEquals(enabled, other.enabled) && _deepEquals(updateAvailable, other.updateAvailable) && _deepEquals(compatible, other.compatible) && _deepEquals(rollbackAvailable, other.rollbackAvailable) && _deepEquals(minHostVersionCode, other.minHostVersionCode) && _deepEquals(maxHostVersionCode, other.maxHostVersionCode) && _deepEquals(permissions, other.permissions) && _deepEquals(permissionsDescription, other.permissionsDescription) && _deepEquals(dependencies, other.dependencies) && _deepEquals(tags, other.tags) && _deepEquals(screenshots, other.screenshots) && _deepEquals(changelog, other.changelog) && _deepEquals(detailsJson, other.detailsJson) && _deepEquals(privacyJson, other.privacyJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeModule(id: $id, name: $name, shortDescription: $shortDescription, description: $description, versionName: $versionName, versionCode: $versionCode, installedVersionCode: $installedVersionCode, runtime: $runtime, deliveryType: $deliveryType, state: $state, route: $route, entryClass: $entryClass, entry: $entry, serviceType: $serviceType, launcherId: $launcherId, iconUrl: $iconUrl, category: $category, fileSize: $fileSize, builtIn: $builtIn, required: $required, featured: $featured, enabled: $enabled, updateAvailable: $updateAvailable, compatible: $compatible, rollbackAvailable: $rollbackAvailable, minHostVersionCode: $minHostVersionCode, maxHostVersionCode: $maxHostVersionCode, permissions: $permissions, permissionsDescription: $permissionsDescription, dependencies: $dependencies, tags: $tags, screenshots: $screenshots, changelog: $changelog, detailsJson: $detailsJson, privacyJson: $privacyJson)';
  }
}

class NativeCatalog {
  NativeCatalog({
    this.schemaVersion,
    this.catalogVersion,
    this.generatedAt,
    this.source,
    this.offline,
    this.modules,
  });

  int? schemaVersion;

  int? catalogVersion;

  String? generatedAt;

  String? source;

  bool? offline;

  List<NativeModule?>? modules;

  List<Object?> _toList() {
    return <Object?>[
      schemaVersion,
      catalogVersion,
      generatedAt,
      source,
      offline,
      modules,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCatalog decode(Object result) {
    result as List<Object?>;
    return NativeCatalog(
      schemaVersion: result[0] as int?,
      catalogVersion: result[1] as int?,
      generatedAt: result[2] as String?,
      source: result[3] as String?,
      offline: result[4] as bool?,
      modules: (result[5] as List<Object?>?)?.cast<NativeModule?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCatalog || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(schemaVersion, other.schemaVersion) && _deepEquals(catalogVersion, other.catalogVersion) && _deepEquals(generatedAt, other.generatedAt) && _deepEquals(source, other.source) && _deepEquals(offline, other.offline) && _deepEquals(modules, other.modules);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeCatalog(schemaVersion: $schemaVersion, catalogVersion: $catalogVersion, generatedAt: $generatedAt, source: $source, offline: $offline, modules: $modules)';
  }
}

class NativeModuleError {
  NativeModuleError({
    this.errorCode,
    this.message,
    this.moduleId,
    this.runtime,
    this.recoverable,
    this.suggestedAction,
    this.technicalDetails,
  });

  String? errorCode;

  String? message;

  String? moduleId;

  String? runtime;

  bool? recoverable;

  String? suggestedAction;

  String? technicalDetails;

  List<Object?> _toList() {
    return <Object?>[
      errorCode,
      message,
      moduleId,
      runtime,
      recoverable,
      suggestedAction,
      technicalDetails,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeModuleError decode(Object result) {
    result as List<Object?>;
    return NativeModuleError(
      errorCode: result[0] as String?,
      message: result[1] as String?,
      moduleId: result[2] as String?,
      runtime: result[3] as String?,
      recoverable: result[4] as bool?,
      suggestedAction: result[5] as String?,
      technicalDetails: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeModuleError || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(errorCode, other.errorCode) && _deepEquals(message, other.message) && _deepEquals(moduleId, other.moduleId) && _deepEquals(runtime, other.runtime) && _deepEquals(recoverable, other.recoverable) && _deepEquals(suggestedAction, other.suggestedAction) && _deepEquals(technicalDetails, other.technicalDetails);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeModuleError(errorCode: $errorCode, message: $message, moduleId: $moduleId, runtime: $runtime, recoverable: $recoverable, suggestedAction: $suggestedAction, technicalDetails: $technicalDetails)';
  }
}

class NativeOperationResult {
  NativeOperationResult({
    this.success,
    this.module,
    this.error,
  });

  bool? success;

  NativeModule? module;

  NativeModuleError? error;

  List<Object?> _toList() {
    return <Object?>[
      success,
      module,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeOperationResult decode(Object result) {
    result as List<Object?>;
    return NativeOperationResult(
      success: result[0] as bool?,
      module: result[1] as NativeModule?,
      error: result[2] as NativeModuleError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeOperationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(success, other.success) && _deepEquals(module, other.module) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeOperationResult(success: $success, module: $module, error: $error)';
  }
}

class NativeDownloadProgress {
  NativeDownloadProgress({
    this.moduleId,
    this.downloadedBytes,
    this.totalBytes,
    this.speedKbps,
    this.percent,
    this.state,
  });

  String? moduleId;

  int? downloadedBytes;

  int? totalBytes;

  int? speedKbps;

  int? percent;

  String? state;

  List<Object?> _toList() {
    return <Object?>[
      moduleId,
      downloadedBytes,
      totalBytes,
      speedKbps,
      percent,
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeDownloadProgress decode(Object result) {
    result as List<Object?>;
    return NativeDownloadProgress(
      moduleId: result[0] as String?,
      downloadedBytes: result[1] as int?,
      totalBytes: result[2] as int?,
      speedKbps: result[3] as int?,
      percent: result[4] as int?,
      state: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeDownloadProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(moduleId, other.moduleId) && _deepEquals(downloadedBytes, other.downloadedBytes) && _deepEquals(totalBytes, other.totalBytes) && _deepEquals(speedKbps, other.speedKbps) && _deepEquals(percent, other.percent) && _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeDownloadProgress(moduleId: $moduleId, downloadedBytes: $downloadedBytes, totalBytes: $totalBytes, speedKbps: $speedKbps, percent: $percent, state: $state)';
  }
}

class NativeModuleEvent {
  NativeModuleEvent({
    this.eventType,
    this.moduleId,
    this.runtime,
    this.state,
    this.timestampMillis,
    this.progress,
    this.error,
  });

  String? eventType;

  String? moduleId;

  String? runtime;

  String? state;

  int? timestampMillis;

  NativeDownloadProgress? progress;

  NativeModuleError? error;

  List<Object?> _toList() {
    return <Object?>[
      eventType,
      moduleId,
      runtime,
      state,
      timestampMillis,
      progress,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeModuleEvent decode(Object result) {
    result as List<Object?>;
    return NativeModuleEvent(
      eventType: result[0] as String?,
      moduleId: result[1] as String?,
      runtime: result[2] as String?,
      state: result[3] as String?,
      timestampMillis: result[4] as int?,
      progress: result[5] as NativeDownloadProgress?,
      error: result[6] as NativeModuleError?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeModuleEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(eventType, other.eventType) && _deepEquals(moduleId, other.moduleId) && _deepEquals(runtime, other.runtime) && _deepEquals(state, other.state) && _deepEquals(timestampMillis, other.timestampMillis) && _deepEquals(progress, other.progress) && _deepEquals(error, other.error);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeModuleEvent(eventType: $eventType, moduleId: $moduleId, runtime: $runtime, state: $state, timestampMillis: $timestampMillis, progress: $progress, error: $error)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeModule) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeCatalog) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is NativeModuleError) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeOperationResult) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is NativeDownloadProgress) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is NativeModuleEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeModule.decode(readValue(buffer)!);
      case 130:
        return NativeCatalog.decode(readValue(buffer)!);
      case 131:
        return NativeModuleError.decode(readValue(buffer)!);
      case 132:
        return NativeOperationResult.decode(readValue(buffer)!);
      case 133:
        return NativeDownloadProgress.decode(readValue(buffer)!);
      case 134:
        return NativeModuleEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ModuleStoreHostApi {
  /// Constructor for [ModuleStoreHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ModuleStoreHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeCatalog> getCatalog() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.getCatalog$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeCatalog;
  }

  Future<NativeCatalog> refreshCatalog() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.refreshCatalog$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeCatalog;
  }

  Future<List<NativeModule?>> getInstalledModules() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.getInstalledModules$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeModule?>();
  }

  Future<NativeModule> getModuleStatus(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.getModuleStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeModule;
  }

  Future<NativeModule> getModuleDetails(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.getModuleDetails$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeModule;
  }

  Future<NativeOperationResult> downloadModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.downloadModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> cancelDownload(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.cancelDownload$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> installModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.installModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> updateModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.updateModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> uninstallModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.uninstallModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> enableModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.enableModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> disableModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.disableModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> rollbackModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.rollbackModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeOperationResult> openModule(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.openModule$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeOperationResult;
  }

  Future<NativeDownloadProgress> getDownloadProgress(String moduleId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.getDownloadProgress$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[moduleId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeDownloadProgress;
  }

  Future<List<NativeModule?>> getUpdateableModules() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.getUpdateableModules$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeModule?>();
  }

  Future<List<NativeOperationResult?>> updateAllModules() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.updateAllModules$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeOperationResult?>();
  }

  Future<String> getUiPreference(String key) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.getUiPreference$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[key]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> setUiPreference(String key, String value) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.setUiPreference$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[key, value]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> openLegacyStore() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreHostApi.openLegacyStore$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class ModuleStoreFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onModuleEvent(NativeModuleEvent event);

  static void setUp(ModuleStoreFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.game_matrix_flutter_store.ModuleStoreFlutterApi.onModuleEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final NativeModuleEvent arg_event = args[0]! as NativeModuleEvent;
          try {
            api.onModuleEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
