plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gamecenter.app.game2048'
    compileSdk 35

    defaultConfig {
        applicationId "com.gamecenter.app.game2048"
        minSdk 26
        targetSdk 35
        versionCode 100
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    compileOnly project(':core:common')
    compileOnly project(':模块商店:功能模块:游戏:games')

    compileOnly 'androidx.appcompat:appcompat:1.6.1'
    compileOnly 'com.google.android.material:material:1.9.0'
    compileOnly 'androidx.fragment:fragment:1.5.0'
}
